from algebraeon import *

assert(Int(-12).factor().sign() == -1)
assert(Int(-2).factor().sign() == -1)
assert(Int(-1).factor().sign() == -1)
assert(Int(0).factor().sign() == 0)
assert(Int(1).factor().sign() == 1)
assert(Int(2).factor().sign() == 1)
assert(Int(12).factor().sign() == 1)

assert(Int(-12).factor().powers() == {2 : 2, 3 : 1})
assert(Int(-2).factor().powers() == {2 : 1})
assert(Int(-1).factor().powers() == {})
assert(Int(0).factor().powers() is None)
assert(Int(1).factor().powers() == {})
assert(Int(2).factor().powers() == {2 : 1})
assert(Int(12).factor().powers() == {2 : 2, 3 : 1})

assert(Int(-12).factor().primes() == [2, 2, 3])
assert(Int(-2).factor().primes() == [2])
assert(Int(-1).factor().primes() == [])
assert(Int(0).factor().primes() is None)
assert(Int(1).factor().primes() == [])
assert(Int(2).factor().primes() == [2])
assert(Int(12).factor().primes() == [2, 2, 3])

assert(Int(-12).factor().distinct_primes() == [2, 3])
assert(Int(-2).factor().distinct_primes() == [2])
assert(Int(-1).factor().distinct_primes() == [])
assert(Int(0).factor().distinct_primes() is None)
assert(Int(1).factor().distinct_primes() == [])
assert(Int(2).factor().distinct_primes() == [2])
assert(Int(12).factor().distinct_primes() == [2, 3])

assert(Int(-4).is_prime() == False)
assert(Int(-3).is_prime() == True)
assert(Int(-2).is_prime() == True)
assert(Int(-1).is_prime() == False)
assert(Int(0).is_prime() == False)
assert(Int(1).is_prime() == False)
assert(Int(2).is_prime() == True)
assert(Int(3).is_prime() == True)
assert(Int(4).is_prime() == False)